---
output: 
  github_document:
    toc: false
    fig_width: 10.08
    fig_height: 6
editor_options: 
  chunk_output_type: console
---


```{r, echo = FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(cowplot)
library(easystats)

options(digits=2)

knitr::opts_chunk$set(
  collapse = TRUE,
  dpi=450,
  fig.path = "figures/"
)
```

# How to Preprocess ECG, RSP and EDA Signals: A Simulation Study


The closest to 0, the better. 


## Respiration (RSP)

### Convenience Functions

<details><summary>See code</summary>
<p>
```{r, echo = TRUE, warning=FALSE, message=FALSE}
plot_effectnoise <- function(df){
  
  geoms <- function(p){
    p + 
      geom_point2(size=2, alpha=0.1) +
      theme_modern() +
      scale_color_viridis_d(guide=FALSE)
  }
  
  # fig1 <- geoms(ggplot(df, aes(x = Noise_Frequency, y = Difference_Rate_Mean, color=Noise_Amplitude)))
  fig2 <- geoms(ggplot(df, aes(x = Noise_Amplitude, y = Difference_Rate_Mean, color=Noise_Frequency)))
  # fig3 <- geoms(ggplot(df, aes(x = Noise_Frequency, y = Difference_Cleaned_Mean, color=Noise_Amplitude)))
  fig4 <- geoms(ggplot(df, aes(x = Noise_Amplitude, y = Difference_Cleaned_Mean, color=Noise_Frequency)))
  
  # cowplot::plot_grid(fig1, fig2, fig3, fig4, nrow=2)
  cowplot::plot_grid(fig2, fig4)
}
```
</p>
</details>



### Filtering

<details><summary>See code</summary>
<p>
```{r, echo = TRUE, warning=FALSE, message=FALSE}
df <- read.csv("data_RSP_filtering.csv")

plot_effectnoise(df)
```
</p>
</details>


#### Filter Type



<details><summary>See code</summary>
<p>
```{r, echo = TRUE, warning=FALSE, message=FALSE}
data <- select(df, Difference_Cleaned_Mean, Difference_Rate_Mean, Filter_Type)
m1 <- lm(Difference_Rate_Mean ~ Filter_Type, data=data[complete.cases(data),])
m2 <- lm(Difference_Cleaned_Mean ~ Filter_Type, data=data[complete.cases(data),])

table <- m1 %>% 
  estimate_means() %>% 
  mutate(Index = "Rate Difference") %>% 
  rbind(m2 %>% 
          estimate_means() %>% 
          mutate(Index = "Signal Difference")) %>% 
  mutate(Index = fct_relevel(Index, "Signal Difference", "Rate Difference"))

fig <- table %>% 
  filter(!is.na(Mean), Filter_Type!="None") %>% 
  ggplot(aes(x = Filter_Type, y = Mean, color=Filter_Type)) +
  geom_line(aes(group=1), position = position_dodge(width = 0.2)) +
  geom_pointrange(aes(ymin=CI_low, ymax=CI_high), position = position_dodge(width=0.2)) +
  # geom_hline(yintercept=0, linetype="dotted") +
  theme_modern() +
  ylab("Mean Difference") +
  scale_color_viridis_d(guide = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust=1),
        axis.title.y = element_blank(),
        strip.placement = "outside") +
  facet_wrap(~Index, scales = "free_y", nrow = 2, strip.position = "left")
```
</p>
</details>
```{r, echo = FALSE, warning=FALSE, message=FALSE}
fig
```

```{r, echo = FALSE, warning=FALSE, message=FALSE}
table %>% 
  mutate(Diff = abs(Mean)) %>%
  group_by(Index) %>% 
  top_n(-5, Diff) %>% 
  select(Index, Filter_Type, Mean) %>% 
  arrange(desc(Index), abs(Mean))
```


#### Filter Band

<details><summary>See code</summary>
<p>
```{r, echo = TRUE, warning=FALSE, message=FALSE}
data <- df %>% 
  select(Difference_Cleaned_Mean, Difference_Rate_Mean, Filter_Type, Filter_Band) %>% 
  filter(Filter_Type %in% c("FIR", "Bessel_9", "Butterworth_9"))
m1 <- lm(Difference_Rate_Mean ~ Filter_Type * Filter_Band, data=data[complete.cases(data),])
m2 <- lm(Difference_Cleaned_Mean ~ Filter_Type * Filter_Band, data=data[complete.cases(data),])

table <- m1 %>% 
  estimate_means() %>% 
  mutate(Index = "Rate Difference") %>% 
  rbind(m2 %>% 
          estimate_means() %>% 
          mutate(Index = "Signal Difference")) %>% 
  mutate(Index = fct_relevel(Index, "Signal Difference", "Rate Difference")) %>%
  separate(Filter_Band, c("Low", "High"), ", ", remove=FALSE) 

fig <- table %>% 
  filter(!is.na(Mean), Filter_Type!="None") %>% 
  ggplot(aes(x = Filter_Type, y = Mean, color=Low, shape=High)) +
  # geom_pointrange(aes(ymin=CI_low, ymax=CI_high), position = position_dodge(width=0.3)) +
  geom_point(position = position_dodge(width=0.5), size=4) +
  # geom_line(aes(group=Filter_Band))  +
  geom_hline(aes(yintercept=0), linetype="dotted") +
  theme_modern() +
  ylab("Mean Difference") +
  scale_color_viridis_d() +
  theme(axis.text.x = element_text(angle = 45, hjust=1),
        axis.title.y = element_blank(),
        strip.placement = "outside") +
  facet_wrap(~Index, scales = "free_y", nrow = 2, strip.position = "left")
```
</p>
</details>
```{r, echo = FALSE, warning=FALSE, message=FALSE}
fig
```


#### Best Filter Parameters

```{r, echo = FALSE, warning=FALSE, message=FALSE}
table %>% 
  mutate(Diff = abs(Mean)) %>%
  group_by(Index) %>% 
  top_n(-6, Diff) %>% 
  select(Index, Filter_Type, Filter_Band, Mean) %>% 
  arrange(Index, abs(Mean))
```
