name-template: '$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

# This automatically suggests the next version based on PR labels
version-resolver:
  default: patch

# This automatically labels PRs based on their title (saves you time!)
autolabeler:
  - label: 'bug'
    title: ['/(bug|fix|fixed|fixes)/i']
  - label: 'feature'
    title: ['/(feature|new|add)/i']
  - label: 'docs'
    title: ['/(docs|documentation|readme)/i']

categories:
  - title: '🚀 Features & Enhancements'
    semver-increment: 'minor'
    when:
      labels: ['feature', 'enhancement']
  - title: '🐛 Bug Fixes'
    semver-increment: 'patch'
    when:
      labels: ['bug', 'fix']
  - title: '📖 Documentation'
    when:
      labels: ['docs', 'documentation']
  - title: '🛠 Maintenance & CI'
    when:
      labels: ['chore', 'ci', 'dependencies']

  # Labels that only influence the next version, without a changelog section
  - type: 'version-resolver'
    semver-increment: 'major'
    when:
      labels: ['major', 'breaking']
  - type: 'version-resolver'
    semver-increment: 'minor'
    when:
      labels: ['minor']
  - type: 'version-resolver'
    semver-increment: 'patch'
    when:
      labels: ['patch']

template: |
  ## 🚀 What’s New

  For a detailed record of changes, see the [NEWS](https://github.com/neuropsychology/NeuroKit/blob/master/NEWS.rst) file.

  $CHANGES

  ## 👏 Thanks to the contributors

  $CONTRIBUTORS
