engines:
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
      E302:
        enabled: false
      E303:
        enabled: false


checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: true
  method-complexity:
    enabled: false
  method-count:
    enabled: true
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: true
  similar-code:
    enabled: false
  identical-code:
    enabled: true

exclude_patterns:
- "tests/"
- "scripts/"
- "data/"