---
output: html_document
editor_options:
  chunk_output_type: console
---

## Introduction

The aim is to assess the optimal complexity parameters.


## Methods

## Results

```{r eval=FALSE, include=FALSE}
library(tidyverse)
library(easystats)
library(patchwork)
```


### Optimization of Delay


```{r warning=FALSE, message=FALSE}
data_delay <- read.csv("data_delay.csv") |> 
  mutate(Metric = str_remove_all(Metric, fixed(" (FFT)")),
         Value = Value/SamplingRate*1000) |> 
  mutate(Area = str_remove_all(Channel, "[:digit:]|z"),
         Area = substring(Channel, 1, 1),
         Area = case_when(Area == "I" ~ "O",
                          Area == "A" ~ "F",
                          TRUE ~ Area))
         

# summarize(group_by(data_delay, Dataset), Value = max(Value, na.rm=TRUE))

# summary_delay <- data_delay %>% 
#   group_by(Dataset, Participant, Channel) %>% 
#   summarise(Optimal = mean(Optimal),
#             Max = max(Scores))
```

#### Per Channel

```{r warning=FALSE, message=FALSE}
delay_perchannel <- function(data_delay, dataset="Lemon") {
  data <- filter(data_delay, Dataset == dataset)
  
  by_channel <- data |> 
    group_by(Condition, Metric, Area, Channel, Value) |> 
    summarise_all(mean, na.rm=TRUE) 
  by_area <- data |> 
    group_by(Condition, Metric, Area, Value) |> 
    summarise_all(mean, na.rm=TRUE) 
  
  by_channel |> 
    ggplot(aes(x = Value, y = Score, color = Area)) +
    geom_line(aes(group=Channel), alpha = 0.20) +
    geom_line(data=by_area, aes(group=Area), size=1) +
    # geom_vline(xintercept = 10, linetype = "dashed", size = 0.5) +
    facet_wrap(~Metric*Condition, scales = "free_y") +
    see::scale_color_flat_d(palette = "rainbow") +
    scale_y_continuous(expand = c(0, 0)) +
    labs(title = paste0("Dataset: ", dataset), x = NULL, y = NULL) +
    guides(colour = guide_legend(override.aes = list(alpha = 1))) +
    see::theme_modern() +
    theme(plot.title = element_text(face = "plain", hjust = 0))
}

p1 <- delay_perchannel(data_delay, dataset="Lemon")
p2 <- delay_perchannel(data_delay, dataset="Texas")

p1 / p2 + plot_annotation(title = "Optimization of Delay", theme = theme(plot.title = element_text(hjust = 0.5, face = "bold")))
```

#### Per Subject

```{r warning=FALSE, message=FALSE}
delay_persubject <- function(data_delay, dataset="Lemon") {
  data <- filter(data_delay, Dataset == dataset)
  
  by_subject <- data |> 
    group_by(Metric, Area, Participant, Value) |> 
    summarise_all(mean) 
  by_area <- data |> 
    group_by(Metric, Area, Value) |> 
    summarise_all(mean) 
  
  by_subject |> 
    mutate(group = paste0(Participant, Area)) |> 
    ggplot(aes(x = Value, y = Score, color = Area)) +
    geom_line(aes(group=group), alpha = 0.20) +
    geom_line(data=by_area, aes(group=Area), size=1) +
    # geom_vline(xintercept = 10, linetype = "dashed", size = 0.5) +
    facet_wrap(~Metric, scales = "free_y") +
    see::scale_color_flat_d(palette = "rainbow") +
    scale_y_continuous(expand = c(0, 0)) +
    labs(title = paste0("Dataset: ", dataset), x = NULL, y = NULL) +
    guides(colour = guide_legend(override.aes = list(alpha = 1))) +
    see::theme_modern() +
    theme(plot.title = element_text(face = "bold", hjust = 0.5))
}
p1 <- delay_persubject(data_delay, dataset="Lemon")
p2 <- delay_persubject(data_delay, dataset="Texas")
```
