name: "📖 Documentation"

on:
    push:
        branches: [master]
    pull_request:
        branches: [master, dev]

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            MNE_DATA: ${{ github.workspace }}/mne_data

        steps:
            - name: Checkout Code
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0

            - name: Install uv
              uses: astral-sh/setup-uv@v9.0.0
              with:
                  enable-cache: true
                  prune-cache: true
                  cache-suffix: docs
                  python-version: "3.13"

            - name: Cache MNE Data
              id: cache-mne
              uses: actions/cache@v6
              with:
                  path: ${{ env.MNE_DATA }}
                  key: mne-datasets-v1

            - name: Install dependencies
              run: uv sync --group docs --extra full

            - name: Download MNE Data (if required)
              if: steps.cache-mne.outputs.cache-hit != 'true'
              run: |
                  mkdir -p ${{ env.MNE_DATA }}
                  uv run python -c "
                  import mne;
                  mne.datasets.sample.data_path(verbose=True);
                  mne.datasets.fetch_fsaverage(verbose=True);
                  mne.datasets.testing.data_path(verbose=True);
                  "

            - name: Build documentation
              run: uv run sphinx-build --keep-going -j 2 -b html docs/ docs/_build/html

            - name: Upload Artifact
              uses: actions/upload-pages-artifact@v5
              with:
                  path: docs/_build/html

    deploy:
        needs: build
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        permissions:
            pages: write
            id-token: write

        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v5
